tasks:
- init: |
    python3 -m venv /workspace/venv
    source /workspace/venv/bin/activate
    pip install --upgrade pip
    make dev_install
    cd /workspace
    zip -qr venv.zip venv
    rm -fr venv
- command: |
    cd /workspace
    unzip -q venv.zip
    source /workspace/venv/bin/activate
    cd /workspace/dagster

ports:
  - port: 3000
    onOpen: open-browser
