version: 2

models:
  - name: story_daily_stats
    description: Summary of posting activity by day
    columns:
      - name: date
        description: The date that the stories were posted on.
        data_type: timestamp
      - name: num_stories
        description: The number of stories posted.
        data_type: integer
      - name: posting_users
        description: The number of unique users who posted a story.
        data_type: integer
  - name: comment_daily_stats
    description: Summary of comment activity by day
    columns:
      - name: date
        description: The date that the stories were posted on.
        data_type: timestamp
      - name: num_comments
        description: The number of comments posted.
        data_type: integer
      - name: commenting_users
        description: The number of unique users who posted a comment.
        data_type: integer
  - name: activity_daily_stats
    description: Combined stats about activity on each day
    columns:
      - name: date
        description: The date that we're measuring activity on.
        data_type: timestamp
      - name: num_comments
        description: The number of comments posted.
        data_type: integer
      - name: commenting_users
        description: The number of unique users who posted a comment.
        data_type: integer
      - name: num_stories
        description: The number of stories posted.
        data_type: integer
      - name: posting_users
        description: The number of unique users who posted a story.
        data_type: integer
